"""Backend protocol — interface that all audio backends implement."""

from pathlib import Path
from typing import Protocol


class Backend(Protocol):
    name: str

    def load(self, path: Path) -> bool: ...
    def play(self) -> bool: ...
    def pause(self) -> None: ...
    def stop(self) -> None: ...
    def seek(self, pos: float) -> None: ...
    def set_volume(self, vol: float) -> None: ...
    def poll_ended(self) -> bool:
        """Return True if the backend knows playback has finished."""
        ...
    def cleanup(self) -> None: ...
